### ISSUE TITLE
Getting  'removeEventListener' of null in Nextjs

### ISSUE THREAD

**Issue by Beedhan** [RobertBroersma/funk#1]
Hi, I am getting "TypeError: Cannot read property 'removeEventListener' of null" in next js when page loads.
And the error is on Tabs.tsx at line 228

**Comment by RobertBroersma** [comment]
Hi @Beedhan thanks for reporting.

Would you mind creating a Codesandbox that has the error? I can't seem to reproduce this myself!

**Comment by Beedhan** [comment]
I was unable to recreate the error in codesandbox but here is video and screen shot of error:
https://imgur.com/a/jsaMaS1
![image](https://user-images.githubusercontent.com/45665443/100625110-426e7b80-334c-11eb-995d-cb1104a0e6ce.png)
```

And Package.json
{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@statikly/funk": "^0.2.0",
    "framer-motion": "^2.9.4",
    "next": "10.0.1",
    "postcss-cli": "^8.3.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-slick": "^0.27.13",
    "slick-carousel": "^1.8.1",
    "tailwindcss": "^2.0.1"
  },
  "devDependencies": {
    "@fullhuman/postcss-purgecss": "^3.0.0",
    "autoprefixer": "^10.0.2",
    "dotenv-webpack": "^5.1.0",
    "postcss": "^8.1.7",
    "postcss-preset-env": "^6.7.0"
  }
}

```

**Comment by RobertBroersma** [comment]
Can you share your code? Preferably reduced to the minimal relevant parts.

**Comment by Beedhan** [comment]
I think the problem lies in "[id].js" where funk exits so, here is path to the tabs

```
export default function productPage({ product }) {
  return (
    <Layout>
    <Head>
      <title >{product.itemName}</title>
    </Head>
    <div>
        <ProductContainerLeft product={product} />
      </div>
    </Layout>
  );
}

productPage.getInitialProps = async ({ query }) => {
  const itemName = query.id.replace(/-/g, " ");
  const res = await fetch(`${process.env.API}/items/?itemName=${itemName}`);
  const data = await res.json();
  return {
    product: data[0],
  };
};
```
```
export default function ProductContainerLeft({ product }) {
  const variants = {
    initial: {
      y: 100,
      opacity: 0,
    },
    animate: {
      y: 0,
      opacity: 100,
    },
  };
  return (
    <motion.div initial="initial" animate="animate" variants={variants}>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-12 border-b-2 mt-10">
        <ProductCarosel product={product} />
       <ProductContainerRight product={product} />
      </div>
      <ProductDescription />
    </motion.div>
  );
}

```

```
import { TabGroup } from '@statikly/funk'

export default function ProductDescription() {
  return (
    <div className="mt-5 flex flex-col m-0 sm:m-20 w-full">
      <TabGroup numTabs={3} direction={TabGroup.direction.HORIZONTAL}>
        <TabGroup.TabList>
          <TabGroup.Tab
            index={0}
            className="h-12  transition-colors duration-150 focus:outline-none w-96"
            activeClassName="activeTabColor text-white"
            inactiveClassName="text-black"
          >
            Description
          </TabGroup.Tab>
          <TabGroup.Tab
            index={1}
            className="h-12  transition-colors duration-150 focus:outline-none w-96"
            activeClassName="activeTabColor text-white"
            inactiveClassName="text-black"
          >
            Details
          </TabGroup.Tab>
          <TabGroup.Tab
            index={2}
            className="h-12  transition-colors duration-150 focus:outline-none w-96"
            activeClassName="activeTabColor text-white"
            inactiveClassName="text-black"
          >
            Delivery 
          </TabGroup.Tab>
        </TabGroup.TabList>
        <TabGroup.TabPanel
          index={0}
          className="p-16 transition-all transform h-64"
          activeClassName="opacity-100 duration-500 translate-x-0"
          inactiveClassName="absolute opacity-0 -translate-x-2"
        >
          This is a Description
        </TabGroup.TabPanel>
        <TabGroup.TabPanel
          index={1}
          className="p-16 transition-all transform h-64 flex flex-col"
          activeClassName="opacity-100 duration-500 translate-x-0"
          inactiveClassName="absolute opacity-0 -translate-x-2"
        >
         This is a Size
        </TabGroup.TabPanel>
        <TabGroup.TabPanel
          index={2}
          className="p-16 transition-all transform h-64"
          activeClassName="opacity-100 duration-500 translate-x-0"
          inactiveClassName="absolute opacity-0 -translate-x-2"
        >
          This is a Delivery
        </TabGroup.TabPanel>
      </TabGroup>
     
    </div>
  );
}

```

There error shows up when I leave [id] route and go to any other route

**Comment by RobertBroersma** [comment]
I have a hunch that this is caused by framer motion `AnimatePresence`, are you using that? Could you try swapping out that `motion.div` with a regular `div`, or turn off the `AnimatePresence`, just to try?

**Comment by Beedhan** [comment]
Changed `<AnimatePresence exitBeforeEnter>` to `div ` and `motion.div` to `div` but  error still shows up

**Comment by RobertBroersma** [comment]
That's strange. So somehow the `ref` to `TabList` exists after mount, but is `null` before running the unmount cleanup...

I'm afraid I have no idea what's going on there, and it's difficult for me to debug any further without my own reproduction, sorry!

**Comment by Beedhan** [comment]
Hey I have invited you to the repo with error so that you can debug it 
and sorry for late reply

**Comment by geritol** [comment]
Also experiencing this issue with Next.js

**Comment by RobertBroersma** [comment]
Hi @geritol do you by any chance have an isolated reproduction?

**Comment by geritol** [comment]
@RobertBroersma Sadly no, and I went on with using `react-tabs`

**Comment by diegoulloao** [comment]
Any solution for this? I'm having this issue in Next.js too. As @Beedhan says the error occurs when you leave a page with dynamic parameters to go another, in files like [param].js

**Comment by RobertBroersma** [comment]
@diegoulloao Unfortunately I have no other suggestions than the ones already available in this issue.

If you have an isolated reproduction I'd be happy to take a look!

**Comment by diegoulloao** [comment]
> @diegoulloao Unfortunately I have no other suggestions than the ones already available in this issue.
> 
> If you have an isolated reproduction I'd be happy to take a look!

@RobertBroersma , yes of course! If you can help us with that would be really great.
I prepared this in order you can fix the bug 🙏🏻 

https://github.com/diegoulloao/funky-issue

Check the README, you can open the repository directly in Gitpod.

**Comment by RobertBroersma** [comment]
@diegoulloao Thanks, that's very helpful! I'll take a look.

**Comment by RobertBroersma** [comment]
@diegoulloao I've released a fix under `0.3.0`, could you try upgrading to that one? :)

**Comment by diegoulloao** [comment]
@RobertBroersma yeah man, now works like a charm!! 🔥  thank you for all, you saved me a lot of work

**Comment by RobertBroersma** [comment]
@diegoulloao Awesome! No problem :)

For your and future visitor's information:
The problem was that the reference to the `TabList` was `undefined` when unmounting, throwing an error when trying to call `removeEventListeners` on it. I fixed it by just checking if the ref is still there before removing the listeners.

I'm not sure if this could cause a leak somewhere, but I couldn't observe one!

**Comment by kidabu9x** [comment]
I'm using version 0.3.1 and still having same issue. 

Here is my code, can you help me :(

`
export default function Page({ categories, isNotFound }) {
    const [navigations, setNavigations] = useState([]);

    const [items, setItems] = useState([]);
    const [requesting, setRequesting] = useState(false);
    const [isLoaded, setLoaded] = useState(false);


    useEffect(() => {
        getItems();
        setLoaded(true);
        return () => {
            setLoaded(false);
        }
    }, []);


    const getItems = async () => {
        setRequesting(true);
        try {
            const { data } = await getRegulationApi();
            setItems(data);
        } catch (error) {
            console.log(error);
        } finally {
            setRequesting(false);
        }
    }


    return (
        <Layout categories={categories} isNotFound={isNotFound}>
            <div className="container mx-auto px-9 pt-8 pb-24">
                <Breadcrumbs className="mb-8" items={navigations} />
                {items.length > 0 && isLoaded && <>
                    <TabGroup numTabs={items.length} direction={TabGroup.direction.HORIZONTAL}>
                        <TabGroup.TabList>
                            {items.map((data, index) => {
                                return (
                                    <TabGroup.Tab
                                        key={index}
                                        index={index}
                                        className="h-12 px-12 rounded w-1/2 focus:outline-none"
                                        activeClassName="border-b-2 border-green-500 text-green-500"
                                        inactiveClassName="text-gray-700"
                                    >
                                        {data.title}
                                    </TabGroup.Tab>
                                )
                            })}
                        </TabGroup.TabList>
                        {items.map((data, index) => {
                            return (
                                <TabGroup.TabPanel
                                    key={index}
                                    index={index}
                                    className="p-8"
                                    activeClassName="opacity-100"
                                    inactiveClassName="absolute"
                                >
                                    {data.title}
                                </TabGroup.TabPanel>
                            )
                        })}
                    </TabGroup>
                </>}
            </div>
        </Layout>
    );
}
`
